name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 setup-postgresql-ubuntu:
  if: true # false to skip job during debug
  name: Setup PostgreSQL on Ubuntu
  runs-on: ubuntu-latest
  steps:
  - name: Start PostgreSQL on Ubuntu
    run: |
      sudo systemctl start postgresql.service
      pg_isready  
  - name: Create root user
    run: |
      sudo -u postgres psql --command="CREATE USER livro PASSWORD 'livro'"
  - name: Create timetable database
    run: |
      sudo -u postgres createdb --owner=livro kimetsu
      PGPASSWORD=livro psql --username=livro --host=localhost --list kimetsu
  - uses: actions/checkout@v2
  - name: Set up JDK 17
    uses: actions/setup-java@v2
    with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
  - name: Build with Maven
    run: mvn -B package --file pom.xml  